authenticators: "authn-k8s/demo-authenticator,authn"
dataKey: "{{ DATA_KEY }}"
account: "demo-account"

image:
  repository: "cyberark/conjur"
  tag: "latest"
  pullPolicy: Always

ssl:
  hostname: custom.domainname.com

postgres:
  persistentVolume:
    create: false
