---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-svc-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-credentials-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["demo-app-backend-credentials"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-backend-credentials
subjects:
- kind: ServiceAccount
  name: demo-app-svc-account
roleRef:
  kind: Role
  name: backend-credentials-reader
  apiGroup: rbac.authorization.k8s.io
