apiVersion: v1
kind: Namespace
metadata:
  name: testapp

---
kind: Service
apiVersion: v1
metadata:
  name: testapp-db
  namespace: testapp
spec:
  selector:
    app: testapp-db
  ports:
    - port: 5432
      targetPort: 5432
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-db
  labels:
    app: testapp-db
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-db
  template:
    metadata:
      labels:
        app: testapp-db
    spec:
      containers:
      - name: testapp-db
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: 5b3e5f75cb3cdc725fe40318
          - name: POSTGRES_DB
            value: test_app
          - name: POSTGRES_USER
            value: test_app
        volumeMounts:
          - mountPath: /var/lib/postgresql/data:Z
            name: pg-data
    